Spring:
  datasource:
    #url: jdbc:h2:file:./src/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    #url: jdbc:h2:mem:testdb
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courses
    username: admin
    password: Internet12#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
message: Hello from default profile